version: '3.8'
services:
  mbrokerbench:
    build: .
    container_name: mbrokerbench
    volumes:
        - ./export_csv:/app/export_csv 
    ports:
      - "1234:1234" # metrics endpoint
    restart: unless-stopped
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - PUSHGATEWAY_URL=http://pushgateway:9091  
        - PROMETHEUS_URL=http://prometheus:9090

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - mbrokerbench

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped
    depends_on:
      - mbrokerbench

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PROVISIONING_PATH=/etc/grafana/provisioning
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-storage:/var/lib/grafana
    ports:
      - "3001:3000"
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  grafana-storage:
